-- password: 123456
INSERT INTO ACCOUNT (ID, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREATED_ON, CREDENTIALS_EXPIRED, ENABLED, PASSWORD, USERNAME) VALUES (1, FALSE, FALSE, '2018-03-27', FALSE, TRUE, '$2a$10$cYLM.qoXpeAzcZhJ3oXRLu9Slkb61LHyWW5qJ4QKvHEMhaxZ5qCPi', 'user');

INSERT INTO ROLE (ACCOUNT_ID, ROLE) VALUES (1, 'REGISTERED_CUSTOMER');

-- password: 123456
INSERT INTO ACCOUNT (ID, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREATED_ON, CREDENTIALS_EXPIRED, ENABLED, PASSWORD, USERNAME) VALUES (2, FALSE, FALSE, '2018-03-27', FALSE, TRUE, '$2a$10$cYLM.qoXpeAzcZhJ3oXRLu9Slkb61LHyWW5qJ4QKvHEMhaxZ5qCPi', 'admin');

INSERT INTO ROLE (ACCOUNT_ID, ROLE) VALUES (2, 'ADMIN');