INSERT INTO USERS (ID, EMAIL, USERNAME, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES (1, 'user@example.com', 'user', 'Jack', 'Smith', '1234567');

INSERT INTO CUSTOMER (USER_ID) VALUES (1);

INSERT INTO USERS (ID, EMAIL, USERNAME, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES (2, 'admin@example.com', 'user', 'Jack', 'Smith', '1234567');
