INSERT INTO USERS (ID, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (1, 'user@example.com', 'Jack', 'Smith', '1234567');

INSERT INTO ACCOUNT (ID, ACCOUNTEXPIRED, ACCOUNTLOCKED, CREATEDON, CREDENTIALSEXPIRED, ENABLED, PASSWORD, USERNAME, USER_ID) VALUES (1, FALSE, FALSE, '2018-03-27', FALSE, TRUE, 'password', 'user', 1);

INSERT INTO CUSTOMER (USER_ID) VALUES (1);

INSERT INTO ROLE (ACCOUNT_ID, ROLE) VALUES (1, 'REGISTERED_CUSTOMER');