INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (1,'Anchovies','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (2,'Sausage','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (3,'Pepperoni','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (4,'Pepperoni Old World','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (5,'Chicken','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (6,'Meatballs','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (7,'Ham','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (8,'Steak','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (9,'Bacon','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (10,'Beef','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (11,'Salami','USD 1.23',1);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (12,'Spinach','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (13,'Mushrooms','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (14,'Red Onion','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (15,'Onion','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (16,'Banana Peppers','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (17,'Pineapple','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (18,'Jalapeno','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (19,'Black Olive','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (20,'Green Pepper','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (21,'Tomatoes','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (22,'White Sauce','USD 1.23',4);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (23,'Classic Red','USD 1.23',4);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (24,'Sweet Red','USD 1.23',4);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (25,'Spicy Red','USD 1.23',4);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (26,'Roasted Garlic','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (27,'Feta Cheese','USD 1.23',2);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (28,'Cheddar Cheese','USD 1.23',2);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (29,'Shaved Parmesan','USD 1.23',2);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (30,'Parmesan','USD 1.23',2);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (31,'Mozzarella','USD 1.23',2);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (32,'Taco','USD 1.23',4);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (33,'Buffalo','USD 1.23',4);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (34,'Pesto','USD 1.23',4);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (35,'BBQ','USD 1.23',4);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (36,'Goat','USD 1.23',2);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (37,'Ricotta','USD 1.23',2);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (38,'Blue','USD 1.23',2);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (39,'Artichoke','USD 1.23',3);
INSERT INTO ingredient (id,name,price,ingredienttype_id) VALUES (40,'Basil','USD 1.23',3);
